<?php

namespace Database\Seeders;

use App\Models\Radical;
use Illuminate\Database\Seeder;

// All 214 Kangxi radicals, ordered by radical number (= primary key).
// Data: [id, character, stroke_count, meaning_en]
// meaning_zh is left null for now — can be added in a follow-up.
class KangxiRadicalSeeder extends Seeder
{
    public function run(): void
    {
        $radicals = [
            // ── 1 stroke ─────────────────────────────────────────────────────
            [1,   '一', 1, 'one'],
            [2,   '丨', 1, 'line'],
            [3,   '丶', 1, 'dot'],
            [4,   '丿', 1, 'slash'],
            [5,   '乙', 1, 'second / bent'],
            [6,   '亅', 1, 'hook'],
            // ── 2 strokes ────────────────────────────────────────────────────
            [7,   '二', 2, 'two'],
            [8,   '亠', 2, 'lid'],
            [9,   '人', 2, 'person / human'],
            [10,  '儿', 2, 'legs'],
            [11,  '入', 2, 'enter'],
            [12,  '八', 2, 'eight'],
            [13,  '冂', 2, 'wide'],
            [14,  '冖', 2, 'cover'],
            [15,  '冫', 2, 'ice'],
            [16,  '几', 2, 'table'],
            [17,  '凵', 2, 'container'],
            [18,  '刀', 2, 'knife'],
            [19,  '力', 2, 'power / strength'],
            [20,  '勺', 2, 'spoon'],
            [21,  '匕', 2, 'spoon / dagger'],
            [22,  '匚', 2, 'box'],
            [23,  '匸', 2, 'hide'],
            [24,  '十', 2, 'ten'],
            [25,  '卜', 2, 'divination'],
            [26,  '卩', 2, 'seal'],
            [27,  '厂', 2, 'cliff'],
            [28,  '厶', 2, 'private'],
            [29,  '又', 2, 'again / right hand'],
            // ── 3 strokes ────────────────────────────────────────────────────
            [30,  '口', 3, 'mouth'],
            [31,  '囗', 3, 'enclosure'],
            [32,  '土', 3, 'earth / soil'],
            [33,  '士', 3, 'scholar'],
            [34,  '夂', 3, 'go'],
            [35,  '夊', 3, 'go slowly'],
            [36,  '夕', 3, 'evening'],
            [37,  '大', 3, 'big / large'],
            [38,  '女', 3, 'woman'],
            [39,  '子', 3, 'child / son'],
            [40,  '宀', 3, 'roof / house'],
            [41,  '寸', 3, 'inch'],
            [42,  '小', 3, 'small'],
            [43,  '尢', 3, 'lame'],
            [44,  '尸', 3, 'corpse'],
            [45,  '屮', 3, 'sprout'],
            [46,  '山', 3, 'mountain'],
            [47,  '巛', 3, 'river'],
            [48,  '工', 3, 'work'],
            [49,  '己', 3, 'self / oneself'],
            [50,  '巾', 3, 'cloth'],
            [51,  '干', 3, 'dry / shield'],
            [52,  '幺', 3, 'small / tiny'],
            [53,  '广', 3, 'lean-to / shelter'],
            [54,  '廴', 3, 'stride'],
            [55,  '廾', 3, 'two hands'],
            [56,  '弋', 3, 'arrow'],
            [57,  '弓', 3, 'bow'],
            [58,  '彐', 3, 'snout'],
            [59,  '彡', 3, 'beard / hair streaks'],
            [60,  '彳', 3, 'step'],
            // ── 4 strokes ────────────────────────────────────────────────────
            [61,  '心', 4, 'heart / mind'],
            [62,  '戈', 4, 'halberd / spear'],
            [63,  '戶', 4, 'door / household'],
            [64,  '手', 4, 'hand'],
            [65,  '支', 4, 'branch'],
            [66,  '攴', 4, 'rap / tap'],
            [67,  '文', 4, 'script / culture'],
            [68,  '斗', 4, 'dipper'],
            [69,  '斤', 4, 'axe'],
            [70,  '方', 4, 'square / direction'],
            [71,  '无', 4, 'without'],
            [72,  '日', 4, 'sun / day'],
            [73,  '曰', 4, 'say'],
            [74,  '月', 4, 'moon / month'],
            [75,  '木', 4, 'tree / wood'],
            [76,  '欠', 4, 'lack / owe'],
            [77,  '止', 4, 'stop / foot'],
            [78,  '歹', 4, 'bad / corpse'],
            [79,  '殳', 4, 'club / weapon'],
            [80,  '毋', 4, 'do not'],
            [81,  '比', 4, 'compare'],
            [82,  '毛', 4, 'hair / fur'],
            [83,  '氏', 4, 'clan / surname'],
            [84,  '气', 4, 'air / steam'],
            [85,  '水', 4, 'water'],
            [86,  '火', 4, 'fire'],
            [87,  '爪', 4, 'claw'],
            [88,  '父', 4, 'father'],
            [89,  '爻', 4, 'lines / trigram'],
            [90,  '爿', 4, 'split wood'],
            [91,  '片', 4, 'slice / piece'],
            [92,  '牙', 4, 'tooth / fang'],
            [93,  '牛', 4, 'ox / cow'],
            [94,  '犬', 4, 'dog'],
            // ── 5 strokes ────────────────────────────────────────────────────
            [95,  '玄', 5, 'dark / mysterious'],
            [96,  '玉', 5, 'jade'],
            [97,  '瓜', 5, 'melon / gourd'],
            [98,  '瓦', 5, 'tile'],
            [99,  '甘', 5, 'sweet'],
            [100, '生', 5, 'life / grow'],
            [101, '用', 5, 'use'],
            [102, '田', 5, 'field'],
            [103, '疋', 5, 'bolt of cloth'],
            [104, '疒', 5, 'sickness'],
            [105, '癶', 5, 'back-to-back footsteps'],
            [106, '白', 5, 'white'],
            [107, '皮', 5, 'skin / leather'],
            [108, '皿', 5, 'dish / vessel'],
            [109, '目', 5, 'eye'],
            [110, '矛', 5, 'spear / lance'],
            [111, '矢', 5, 'arrow'],
            [112, '石', 5, 'stone / rock'],
            [113, '示', 5, 'spirit / show'],
            [114, '禸', 5, 'tracks'],
            [115, '禾', 5, 'grain / cereal'],
            [116, '穴', 5, 'cave / hole'],
            [117, '立', 5, 'stand'],
            // ── 6 strokes ────────────────────────────────────────────────────
            [118, '竹', 6, 'bamboo'],
            [119, '米', 6, 'rice'],
            [120, '糸', 6, 'silk thread'],
            [121, '缶', 6, 'earthen jar'],
            [122, '网', 6, 'net'],
            [123, '羊', 6, 'sheep / goat'],
            [124, '羽', 6, 'feather / wing'],
            [125, '老', 6, 'old / aged'],
            [126, '而', 6, 'and / yet'],
            [127, '耒', 6, 'plow'],
            [128, '耳', 6, 'ear'],
            [129, '聿', 6, 'pen / writing brush'],
            [130, '肉', 6, 'meat / flesh'],
            [131, '臣', 6, 'minister / vassal'],
            [132, '自', 6, 'self / from'],
            [133, '至', 6, 'arrive / to'],
            [134, '臼', 6, 'mortar'],
            [135, '舌', 6, 'tongue'],
            [136, '舛', 6, 'oppose / error'],
            [137, '舟', 6, 'boat'],
            [138, '艮', 6, 'stopping'],
            [139, '色', 6, 'color'],
            [140, '艸', 6, 'grass / plant'],
            [141, '虍', 6, 'tiger stripes'],
            [142, '虫', 6, 'insect / creature'],
            [143, '血', 6, 'blood'],
            [144, '行', 6, 'walk / go'],
            [145, '衣', 6, 'clothing'],
            [146, '襾', 6, 'cover'],
            // ── 7 strokes ────────────────────────────────────────────────────
            [147, '見', 7, 'see'],
            [148, '角', 7, 'horn / angle'],
            [149, '言', 7, 'speech / words'],
            [150, '谷', 7, 'valley'],
            [151, '豆', 7, 'bean / legume'],
            [152, '豕', 7, 'pig'],
            [153, '豸', 7, 'catlike / fierce animal'],
            [154, '貝', 7, 'shell / money'],
            [155, '赤', 7, 'red'],
            [156, '走', 7, 'walk / run'],
            [157, '足', 7, 'foot / sufficient'],
            [158, '身', 7, 'body'],
            [159, '車', 7, 'cart / vehicle'],
            [160, '辛', 7, 'bitter / spicy'],
            [161, '辰', 7, 'morning / 5th earthly branch'],
            [162, '辵', 7, 'walk / movement'],
            [163, '邑', 7, 'town / city'],
            [164, '酉', 7, 'wine jar / 10th branch'],
            [165, '釆', 7, 'distinguish / gather'],
            [166, '里', 7, 'village / mile'],
            // ── 8 strokes ────────────────────────────────────────────────────
            [167, '金', 8, 'gold / metal'],
            [168, '長', 8, 'long / grow'],
            [169, '門', 8, 'gate / door'],
            [170, '阜', 8, 'mound / hill'],
            [171, '隶', 8, 'attach / follow'],
            [172, '隹', 8, 'short-tailed bird'],
            [173, '雨', 8, 'rain'],
            [174, '青', 8, 'blue-green'],
            [175, '非', 8, 'wrong / not'],
            // ── 9 strokes ────────────────────────────────────────────────────
            [176, '面', 9, 'face / surface'],
            [177, '革', 9, 'leather / reform'],
            [178, '韋', 9, 'tanned leather'],
            [179, '韭', 9, 'chives'],
            [180, '音', 9, 'sound / music'],
            [181, '頁', 9, 'page / head'],
            [182, '風', 9, 'wind'],
            [183, '飛', 9, 'fly'],
            [184, '食', 9, 'eat / food'],
            [185, '首', 9, 'head / first'],
            [186, '香', 9, 'fragrant'],
            // ── 10 strokes ───────────────────────────────────────────────────
            [187, '馬', 10, 'horse'],
            [188, '骨', 10, 'bone'],
            [189, '高', 10, 'high / tall'],
            [190, '髟', 10, 'long hair'],
            [191, '鬥', 10, 'fight / struggle'],
            [192, '鬯', 10, 'sacrificial wine'],
            [193, '鬲', 10, 'tripod / cauldron'],
            [194, '鬼', 10, 'ghost / spirit'],
            // ── 11 strokes ───────────────────────────────────────────────────
            [195, '魚', 11, 'fish'],
            [196, '鳥', 11, 'bird'],
            [197, '鹵', 11, 'salt / brine'],
            [198, '鹿', 11, 'deer'],
            [199, '麥', 11, 'wheat / barley'],
            [200, '麻', 11, 'hemp / flax'],
            // ── 12 strokes ───────────────────────────────────────────────────
            [201, '黃', 12, 'yellow'],
            [202, '黍', 12, 'millet'],
            [203, '黑', 12, 'black'],
            [204, '黹', 12, 'embroidery'],
            // ── 13 strokes ───────────────────────────────────────────────────
            [205, '黽', 13, 'frog'],
            [206, '鼎', 13, 'tripod cauldron'],
            [207, '鼓', 13, 'drum'],
            [208, '鼠', 13, 'rat / mouse'],
            // ── 14 strokes ───────────────────────────────────────────────────
            [209, '鼻', 14, 'nose'],
            [210, '齊', 14, 'even / orderly'],
            // ── 15 strokes ───────────────────────────────────────────────────
            [211, '齒', 15, 'tooth'],
            // ── 16 strokes ───────────────────────────────────────────────────
            [212, '龍', 16, 'dragon'],
            [213, '龜', 16, 'tortoise / turtle'],
            // ── 17 strokes ───────────────────────────────────────────────────
            [214, '龠', 17, 'flute / pipe'],
        ];

        foreach ($radicals as [$id, $char, $strokes, $meaning]) {
            Radical::firstOrCreate(
                ['id' => $id],
                [
                    'character'   => $char,
                    'stroke_count'=> $strokes,
                    'meaning_en'  => $meaning,
                    'meaning_zh'  => null,
                ]
            );
        }
    }
}
