<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('user_saved_examples', function (Blueprint $table) {
            // learner = written by learner + AI verified, generated = AI-generated by 師父
            $table->string('source_type', 20)->default('learner')->after('ai_feedback');
        });
    }

    public function down(): void
    {
        Schema::table('user_saved_examples', function (Blueprint $table) {
            $table->dropColumn('source_type');
        });
    }
};
